<?xml version="1.0" encoding="UTF-8"?><testrun name="CustomerTest" project="junit" tests="1" started="0" failures="0" errors="1" ignored="0">
  <testsuite name="com.db.junit.test.CustomerTest" incomplete="true">
    <error>java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)&#13;
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)&#13;
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)&#13;
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)&#13;
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:718)&#13;
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)&#13;
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)&#13;
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:664)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:247)&#13;
	at com.db.junit.test.CustomerTest.createConnection(CustomerTest.java:73)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.invokeMethod(BeforeAndAfterRunner.java:74)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runBefores(BeforeAndAfterRunner.java:50)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:33)&#13;
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
&#13;
</error>
    <testcase name="testgetCustomers" classname="com.db.junit.test.CustomerTest" incomplete="true"/>
  </testsuite>
</testrun>
